parameters: 
  insprie: 
    serialNum: /dev/GripperDriver1
    # serialNum: /dev/ttyUSB0
    baudrate: 115200
    speed: 500
    force: 50
    size_max: 980
    size_min: 0
    
  airpowere:
    robotIp: 10.10.56.214
    robotPort: 23234
    portIndex: 0
    openVlaue: false
    closeValue: true
