parameters: 
    sorting: false
    followPosture: 
      R: false
      P: false
      Y: false
    grabPosture: 
      DIR_R: -0.2
      DIR_P: 0
      DIR_Y: 0.1
    grabOffset: 
      x: 0.0
      y: -0.06
      z: 0.01
    placePosture: 
      DIR_R: 0
      DIR_P: 0
      DIR_Y: 0
    placeOffset: 
      x: 0
      y: 0
      z: 0
