voxel:
  leafX: 0.01
  leafY: 0.01
  leafZ: 0.01

region:
  maxZ: 1.5
  minZ: 0.5
  maxY: 200
  minY: -200
  maxX: 0.28
  minX: -0.30

object:
  maxZ: 0
  minZ: 0
  maxY: 0
  minY: 0
  maxX: 0
  minX: 0
